// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tamcmkgrvjcyragjwqcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbWNta2dydmpjeXJhZ2p3cWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODA5NzksImV4cCI6MjA2MTg1Njk3OX0.ut4ylw_qmkSWcIBxG_MN8Yc8xAPbvy22WW4ph5O2ZDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);